version: '2'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
      - './init.sh:/docker-entrypoint-initdb.d/init.sh'
    environment:
      - POSTGRES_PASSWORD=mariano
      - POSTGRES_USER=mariano
      - POSTGRES_DB=test
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  load_db:
    build: ./Content/.
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=mariano
      - POSTGRES_USER=mariano
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres


